name: Fei Li
########### Education
education:
  -
    icon: bocconi.png
    school: Bocconi University
    degree: MSc. in Data Science
    loc: Milan, Italy
    time: 2018 ~ 2020 &middot; 2 yrs
    description: >-
      GPA: 110/110 cum laude
      <br>
      Thesis: Some Extensions of Flow Contrastive Estimation
      <br>
      Courses: 
      Statistics and Probability, Machine Learning, 
      Deep Learning, Algorithms, Optimal Control, 
      Stochastic Process, Digital Privacy, Econometrics,
      Game Theory, Advanced Microeconomics
  -
    icon: sdu.png
    school: Shandong University
    degree: Bachelor of Economics
    loc: Jinan, China
    time: 2013 ~ 2017 &middot; 4 yrs
    description: >-
      GPA: 4.01/5.0
      <br>
      Major: Finance
########### Experience
experience:
  -
    icon: abc.png
    company: Agricultural Bank of China
    role: Analyst
    loc: Beijing, China
    time: 2021 ~ now &middot; 1yr
    description: |
      I'm in the Strategic Planning department & Green Finance Research Institute. I conduct research on climate change, environmental protection and sustainable finance. We write book series on green finance development in different Chinese provinces, organize seminars, and regularly produce research reports. Besides research, I also edit and distribute sustainable finance news within our banking group.
  -
    icon: pingan.png
    company: Ping An Technology
    role: Product Manager Intern
    loc: Shenzhen, China
    time: 2020 &middot; 2mos
    description: |
      I completed a marketing research report on edge computing, in which I analyzed market players and their latest technologies. I also inspected production data of a data labeling platform. I successfully detected users' cheating behaviors, and provided solutions. I also drew prototypes using Axure.
  -
    icon: harvard.png
    company: Harvard University
    role: Research Assistant
    loc: Cambridge, USA
    time: 2017 &middot; 4mos
    description: |
      I worked in a team to digitalize thousands of gazetteers at the Harvard-Yenching Library. We scanned thousands of book pages that contain data tables, extracted the data, and cleaned and organized the data with Python for economic research. I also presented an analysis of the population and education data in a seminar.

##########################################################################################
links:
  -
    icon: linkedin.png
    name: LinkedIn
    url: https://www.linkedin.com/in/lifeipro  
  -
    icon: github.svg
    name: GitHub
    url: https://github.com/lifeitech  
  -
    icon: mathstackex.png
    name: Math StackExchange
    url: https://math.stackexchange.com/users/324369/fei-li  
  -
    icon: leetcode.png
    name: LeetCode
    url: https://leetcode-cn.com/u/lifeitech/
  -
    icon: gmail.png
    name: Email
    url: mailto:fei.li.best@gmail.com

programming:
  -
    icon: python.png
    name: Python
    url: 'https://github.com/lifeitech/leetcode'
  -
    icon: pytorch.png
    name: PyTorch
    url: 'https://github.com/lifeitech/nce'
  -
    icon: pyspark.png
    name: PySpark
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/eda.py'
  -
    icon: sklearn.png
    name: sklearn
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/model.py'
  -
    icon: pandas.png
    name: pandas
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/data-aggregation.py'
  -
    icon: numpy.png
    name: numpy
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/model.py'
  -
    icon: scrapy.png
    name: scrapy
    url: 'https://github.com/lifeitech/web-scraping'
  -
    icon: sql.png
    name: sql
    url: 'https://github.com/lifeitech/sql-nowcoder'
  -
    icon: julia.png
    name: Julia
    url: 'https://lifei.tech/posts/julia'
  -
    icon: html.png
    name: HTML
    url: 'https://lifei.tech/'
  -
    icon: css.png
    name: CSS
    url: 'https://github.com/lifeitech/resume/blob/master/style.scss'
  -
    icon: latex.png
    name: LaTeX
    url: 'https://lifei.tech/notes/'