name: Fei Li
########### Education
education:
  -
    icon: bocconi.png
    school: Bocconi University
    degree: MSc. in Data Science 🎓
    loc: Milan, Italy
    time: 2018 ~ 2020 &middot; 2 yrs
    description: >-
      GPA: 110/110 cum laude
      <br>
      Thesis: Some Extensions of Flow Contrastive Estimation
      <br>
      Courses: 
      Database Systems, Statistics and Probability, Machine Learning, 
      Deep Learning, Algorithms, Optimal Control, 
      Stochastic Process, Digital Privacy, Econometrics,
      Game Theory, Advanced Microeconomics
  -
    icon: sdu.png
    school: Shandong University
    degree: Bachelor of Economics 🎓
    loc: Jinan, China
    time: 2013 ~ 2017 &middot; 4 yrs
    description: >-
      GPA: 4.01/5.0
      <br>
      Courses: Calculus, Linear Algebra, Probability and Statistics, Intermediate Microeconomics, Data Analytics with Python

########### Experience
experience:
  -
    icon: abc.png
    company: Agricultural Bank of China
    role: Analyst
    loc: Beijing, China
    time: 2021 ~ now &middot; 1yr
    description: |
      I work in the Strategic Planning department and the Green Finance Research Institute at the headquarter. I conduct research on climate change, environmental protection and sustainable finance. We produce books and research reports, organize seminars and meetings. Besides research, I also edit and distribute news within the banking group.
  -
    icon: pingan.png
    company: Ping An Technology
    role: Product Manager Intern
    loc: Shenzhen, China
    time: 2020 &middot; 2mos
    description: |
      Worked on an AI-translation correction platform. Detected users' fraudulent behaviors from production data, and provided a simple model for automatic detection and prevention.  Drew prototypes with Axure. Finally, also completed a research report on edge computing, as well as several patent proposals.
  -
    icon: harvard.png
    company: Harvard University
    role: Research Assistant
    loc: Cambridge, USA
    time: 2017 &middot; 4mos
    description: |
      I worked in a team to digitalize thousands of Chinese gazetteers at the Harvard-Yenching Library. I scanned thousands of book pages to extract the data with the help of some computer vision software, and cleaned and organized the data with Python. I also presented an analysis of the population and education data in a seminar at Harvard.

##########################################################################################
links:
  -
    icon: linkedin.png
    name: LinkedIn
    url: https://www.linkedin.com/in/lifeipro  
  -
    icon: github.svg
    name: GitHub
    url: https://github.com/lifeitech  
  -
    icon: mathstackex.png
    name: Math StackExchange
    url: https://math.stackexchange.com/users/324369/fei-li  
  -
    icon: leetcode.png
    name: LeetCode
    url: https://leetcode-cn.com/u/lifeitech/
  -
    icon: gmail.png
    name: Email
    url: mailto:fei.li.best@gmail.com

programming:
  -
    icon: python.png
    name: Python
    url: 'https://github.com/lifeitech/leetcode'
  -
    icon: pytorch.png
    name: PyTorch
    url: 'https://github.com/lifeitech/nce'
  -
    icon: pyspark.png
    name: PySpark
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/eda.py'
  -
    icon: sklearn.png
    name: sklearn
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/model.py'
  -
    icon: pandas.png
    name: pandas
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/data-aggregation.py'
  -
    icon: numpy.png
    name: numpy
    url: 'https://github.com/lifeitech/math-stack-analysis/blob/master/code/model.py'
  -
    icon: scrapy.png
    name: scrapy
    url: 'https://github.com/lifeitech/web-scraping'
  -
    icon: sql.png
    name: sql
    url: 'https://github.com/lifeitech/sql-nowcoder'
  -
    icon: julia.png
    name: Julia
    url: 'https://lifei.tech/posts/julia'
  -
    icon: html.png
    name: HTML
    url: 'https://lifei.tech/'
  -
    icon: css.png
    name: CSS
    url: 'https://github.com/lifeitech/resume/blob/master/style.scss'
  -
    icon: latex.png
    name: LaTeX
    url: 'https://lifei.tech/notes/'